---
repos:
  -
    repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.2.3
    hooks:
      -
        id: trailing-whitespace
        stages:
          - commit
          - push
      -
        id: check-merge-conflict
        stages:
          - commit
          - push
      -
        id: check-symlinks
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.15.0
    hooks:
      -
        id: yamllint
        stages:
          - commit
          - push

  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
      - id: cargo-check
  -
    repo: 'https://github.com/jorisroovers/gitlint.git'
    rev: v0.11.0
    hooks:
      -
        id: gitlint
        stages:
          - commit-msg
  -
    repo: local
    hooks:
      -
        id: run-local-test
        name: 'Run tests'
        entry: 'make test'
        language: system
        pass_filenames: false
        types:
          - rust
        stages:
          - commit
          - push
