[package]
name = "advent"
version = "0.1.0"
authors = ["Jean-François Roche <jfroche@affinitic.be>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
regex = "1.3.1"
itertools = "0.8.0"
structopt = "0.3.5"
petgraph = "0.5.0"
